### PR TITLE
MVP `SelectPinboard` design (a.k.a. 'index list')

### PR DESCRIPTION
**Pull request by twrichards**
…according to https://www.figma.com/file/VEGrFKfCnIm11E264QMqae/Pinboard-index?node-id=22%3A2266

## Images
| in composer piece | outside composer piece |
| --- | --- |
| image | image |

Lastly with a payload selected, but without a pinboard chosen... 
image

### CODE REVIEW

**Review by andrew-nowak — APPROVED** [review]

**Comment by jennygrahamjones** [comment]
Very cool to see a little of how far this has come! ❤️

**Comment by twrichards** [comment]
> Very cool to see a little of how far this has come! ❤️

Ahhh @jennygrahamjones - lovely to hear from you, and amazing that you're still following the repo ☺️

The project was on hiatus for around 9 months whilst we did a big project on the grid. During that time @pradasa made some amazing (comprehensive & beautiful) designs. Finally been back working on pinboard (officially that is, still did little side projects on it, e.g. https://github.com/guardian/editorial-tools-pinboard/pull/58) over the last couple of sprints and managed to implement the majority of the designs with @andrew-nowak ... such that we ran our first proper PROD pilot(s) last week with various liveblogs.

How are things in 🇨🇦  ?

**Comment by twrichards** [comment]
@jennygrahamjones I figured this is the easiest way to reach you...

Just wanted to share a little something from the newsletter today: 
image

Also presented it in morning conference this morning, which isn't recorded obvs but I thought you might want to see where it's at these days (with some cringe narration - this was my fallback, narration was live on the day) 

https://github.com/guardian/pinboard/assets/19289579/e031c7f8-7e54-4a5c-bb82-8345ec3cafdf

A shorter version of the video is also on all the TVs in the office (sans narration, thank goodness).

Hope you're well.

**Comment by jennygrahamjones** [comment]
@twrichards thanks so much for tagging me in this! It's so cool to see that this is now something that everyone is able to use, and very kind of you to credit my contributions as part of the update :) If you're able to share, I'd love to know how the various teams are reacting and adapting to Pinboard?

**Comment by twrichards** [comment]
@jennygrahamjones part one (of three) of eng. blog post just dropped: https://www.theguardian.com/info/2024/feb/08/pinboard-transforming-communication-across-the-newsroom-part-1-of-3 next instalments will be tomorrow and Saturday - you are of course credited 😊

> @twrichards thanks so much for tagging me in this! It's so cool to see that this is now something that everyone is able to use, and very kind of you to credit my contributions as part of the update :) If you're able to share, I'd love to know how the various teams are reacting and adapting to Pinboard?

Pinboard is going well, its pretty stable, cheap to run and has a core/frequent user base - we'd like the usage to be more comprehensive but that should come (gradually) in time, and there's a couple of improvements in the pipeline which should help with that.

> I realise I didn't reply to your previous message - things are going well in Canada! We have permanent residency now, and are working towards citizenship. Just moved into a little house (rented) with a garden, which is a lovely change after being in a big block of flats for so long.

Glad to hear things are going well in Canada - I love(d) it there.

**Pull request merged**
